USE hospitaldb;

-- 지역 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_region
(
    REGION_CODE       INT NOT NULL AUTO_INCREMENT COMMENT '지역코드',
    ADDRESS           VARCHAR(50) NOT NULL COMMENT '주소',
    AVERAGE_AGE       FLOAT NOT NULL COMMENT '평균나이',
    CONSTRAINT pk_region PRIMARY KEY (REGION_CODE)
) ENGINE=INNODB COMMENT '지역';

-- 전국병원 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_hospital
(
    REGION_CODE       INT COMMENT '지역코드',
    HOSPITAL_NAME     VARCHAR(50) NOT NULL COMMENT '병원이름',
    DOCTOR_NUM        INT NOT NULL COMMENT '의사수',
	CONSTRAINT fk_hospital FOREIGN KEY (REGION_CODE) REFERENCES tbl_region (REGION_CODE)
) ENGINE=INNODB COMMENT '전국병원';

-- 야간병원 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_night_hospital
(
	HOSPITAL_ID       INT NOT NULL AUTO_INCREMENT COMMENT '병원ID',
    REGION_NAME       VARCHAR(50) NOT NULL COMMENT '지역이름',
    HOSPITAL_NAME     VARCHAR(50) NOT NULL COMMENT '병원이름',
	CONSTRAINT pk_night_hospital PRIMARY KEY (HOSPITAL_ID)
) ENGINE=INNODB COMMENT '야간병원';

-- 암병원 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_cancer_hospital
(
    HOSPITAL_ID       INT NOT NULL COMMENT '병원ID',
    REGION_NAME       VARCHAR(50) NOT NULL COMMENT '지역이름',
    HOSPITAL_NAME     VARCHAR(50) NOT NULL COMMENT '병원이름',
	CONSTRAINT pk_cancer_hospital PRIMARY KEY (HOSPITAL_ID)
) ENGINE=INNODB COMMENT '암병원';

-- 암 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_cancer_type
(
    CANCER_ID         INT NOT NULL COMMENT '암ID',
    CANCER_TYPE       VARCHAR(50) NOT NULL COMMENT '암종류',
	CONSTRAINT pk_cancer_type PRIMARY KEY (CANCER_ID)
) ENGINE=INNODB COMMENT '암';

-- 치료여부 테이블 생성
CREATE TABLE IF NOT EXISTS tbl_cancer_care
(
    HOSPITAL_ID     INT NOT NULL COMMENT '병원ID',
    CANCER_ID       INT NOT NULL COMMENT '암ID',
    ALLOW_TREATMENT BOOLEAN NOT NULL COMMENT '항암치료여부',
    ALLOW_RADIATION BOOLEAN NOT NULL COMMENT '방사선치료여부',
    ALLOW_SURGERY   BOOLEAN NOT NULL COMMENT '수술 여부',
    CONSTRAINT fk_cancer_hs   FOREIGN KEY (HOSPITAL_ID) REFERENCES tbl_cancer_hospital (HOSPITAL_ID),
    CONSTRAINT fk_cancer_care FOREIGN KEY (CANCER_ID) REFERENCES tbl_cancer_type (CANCER_ID)
) ENGINE=InnoDB COMMENT='치료여부';

